use axum::extract::FromRef;
use axum_extra::extract::cookie::Key;
use sqlx::postgres::PgPoolOptions; // Use PgPoolOptions
use sqlx::{FromRow, PgPool}; // Import FromRow and PgPool
use std::env;
use tower_http::services::ServeDir;

#[derive(Clone)]
pub struct AppState {
    key: Key,
    pool: PgPool,
}

impl FromRef<AppState> for Key {
    fn from_ref(state: &AppState) -> Self {
        state.key.clone()
    }
}

impl FromRef<AppState> for PgPool {
    fn from_ref(state: &AppState) -> Self {
        state.pool.clone()
    }
}

// Define a struct matching the 'first_table' columns for fetching
#[derive(FromRow, Debug)]
struct Item {
    id: i32,
    name: String,
}

mod api_routes {
    // This is generated by build.rs
    include!(concat!(env!("OUT_DIR"), "/routes.rs"));
}

#[tokio::main]
async fn main() -> Result<(), sqlx::Error> {
    // Return sqlx::Error
    // Load environment variables from .env file
    dotenvy::dotenv().expect("Failed to read .env file");

    // --- Database Connection and Initial Query ---
    let database_url = env::var("DATABASE_URL").expect("DATABASE_URL must be set");

    // Create a connection pool using PgPoolOptions
    let pool = PgPoolOptions::new()
        .max_connections(5) // Example: Set max connections
        .connect(&database_url)
        .await?; // Use ? for error propagation
    println!("Database connection pool created.");

    // Fetch all items from first_table
    let items = sqlx::query_as::<_, Item>("SELECT id, name FROM first_table ORDER BY id")
        .fetch_all(&pool)
        .await?; // Use ? for error propagation

    // Print the fetched items
    println!("--- Items in first_table ---");
    if items.is_empty() {
        println!("No items found.");
    } else {
        for item in items {
            println!("ID: {}, Name: {}", item.id, item.name);
        }
    }
    println!("----------------------------");
    // --- End Database Connection and Initial Query ---

    // --- Web Server Setup ---
    // Generate a secure key for cookie handling.
    let key = Key::generate();

    // Create the application state.
    // Clone the pool for the AppState, as the original 'pool' might be used elsewhere if needed,
    // though in this setup it's fine to move it directly if preferred.
    let app_state = AppState {
        key,
        pool: pool.clone(),
    };

    // Build the router and provide the state.
    let app = api_routes::build_router()
        .fallback_service(ServeDir::new("public"))
        .with_state(app_state);

    // Bind the listener and serve the application.
    let port = env::var("PORT").unwrap_or_else(|_| "3000".to_string());
    let port = port.parse::<u16>().unwrap_or(3000);

    let listener = tokio::net::TcpListener::bind(format!("0.0.0.0:{}", port))
        .await
        .unwrap(); // Using unwrap here for simplicity, consider proper error handling
    println!("Listening on http://{}", listener.local_addr().unwrap());
    axum::serve(listener, app).await.unwrap(); // Using unwrap here

    Ok(()) // Return Ok(()) at the end of main
}
